services:
  - type: web
    name: mundo-nomada-test
    runtime: docker
    region: frankfurt
    plan: free
    dockerfilePath: ./Dockerfile
    dockerContext: .
    healthCheckPath: /api_php/health.php
    autoDeployTrigger: commit
    envVars:
      - key: MUNDONOMADA_SUPABASE_DSN
        sync: false
      - key: MUNDONOMADA_SUPABASE_USER
        sync: false
      - key: MUNDONOMADA_SUPABASE_PASSWORD
        sync: false
