-- Mundo Nómada: esquema inicial para Supabase PostgreSQL.
-- No contiene datos personales, pedidos ni imágenes reales.

create type public.user_role as enum ('admin', 'user');
create type public.order_status as enum ('pendiente', 'pagado', 'enviado', 'completado', 'cancelado');

create schema if not exists app_private;
revoke all on schema app_private from public;

create table public.users (
  id bigint generated by default as identity primary key,
  name varchar(100) not null,
  email varchar(254) not null,
  password varchar(255) not null,
  role public.user_role not null default 'user',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  remember_token varchar(255),
  token_expiry timestamptz,
  password_updated_at timestamptz
);

create unique index users_email_unique on public.users (lower(email));

create table public.categorias (
  id bigint generated by default as identity primary key,
  nombre varchar(50) not null unique,
  descripcion text
);

create table public.productos (
  id bigint generated by default as identity primary key,
  nombre varchar(100) not null,
  precio numeric(10,2) not null check (precio >= 0),
  descripcion text,
  stock integer not null default 0 check (stock >= 0),
  categoria_id bigint not null references public.categorias(id) on delete restrict,
  imagen_url text,
  color varchar(50),
  talla varchar(10),
  updated_at timestamptz not null default now()
);

create index productos_categoria_idx on public.productos(categoria_id);

create table public.carrito (
  id bigint generated by default as identity primary key,
  user_id bigint not null references public.users(id) on delete cascade,
  producto_id bigint not null references public.productos(id) on delete cascade,
  cantidad integer not null default 1 check (cantidad > 0),
  unique (user_id, producto_id)
);

create index carrito_producto_idx on public.carrito(producto_id);

create table public.orders (
  id bigint generated by default as identity primary key,
  user_id bigint not null references public.users(id) on delete restrict,
  fecha timestamptz not null default now(),
  total numeric(10,2) not null check (total >= 0),
  estado public.order_status not null default 'pendiente',
  payment_reference varchar(191) unique,
  shipping_name varchar(100),
  shipping_address varchar(255),
  shipping_phone varchar(30)
);

create index orders_user_fecha_idx on public.orders(user_id, fecha desc);

create table public.order_items (
  id bigint generated by default as identity primary key,
  order_id bigint not null references public.orders(id) on delete cascade,
  producto_id bigint not null references public.productos(id) on delete restrict,
  cantidad integer not null check (cantidad > 0),
  precio_unitario numeric(10,2) not null check (precio_unitario >= 0)
);

create index order_items_producto_idx on public.order_items(producto_id);

create or replace function app_private.set_updated_at()
returns trigger
language plpgsql
security invoker
set search_path = pg_catalog
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create trigger users_set_updated_at
before update on public.users
for each row execute function app_private.set_updated_at();

create trigger productos_set_updated_at
before update on public.productos
for each row execute function app_private.set_updated_at();

-- Impide que la API de datos de Supabase exponga las tablas por defecto.
-- El acceso continuará pasando por el backend PHP hasta que se implemente
-- Supabase Auth y políticas específicas.
alter table public.users enable row level security;
alter table public.categorias enable row level security;
alter table public.productos enable row level security;
alter table public.carrito enable row level security;
alter table public.orders enable row level security;
alter table public.order_items enable row level security;

revoke all on all tables in schema public from anon, authenticated;
revoke all on all sequences in schema public from anon, authenticated;
